version: 2
jobs:
    build:
        working_directory: /go/src/github.com/livesense-inc/fanlin
        docker:
            - image: golang:latest
                  GO111MODULE: on
                  
        steps:
            - checkout
            - run:
                name: "run test"
                command: |
                    go test ./...

