version: 2
jobs:
    build:
        working_directory: /go/src/github.com/livesense-inc/fanlin
        docker:
            - image: golang:latest
        steps:
            - checkout
            - run:
                name: "run test"
                command: |
                    go test ./...

